version: '3.8'

services:
  homebot:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./homebot:/app/homebot
      - ./network.db:/app/network.db
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
